filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
        - 'languages/*'

before_commands:
    - 'composer install --dev --prefer-source'

tools:
    external_code_coverage: true
    php_code_sniffer: true
    js_hint: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, languages, assets]